### ISSUE TITLE
About hardware requirements (GPU)

### ISSUE THREAD

**Issue by mit-mit-pg** [caiyuanhao1998/SAX-NeRF#4]
Thanks for sharing your wonderful project !!
I was really looking forward to reading the scripts.

I would like to ask about the hardware requirements for training a model.
In your paper, you mentioned that all experiments were performed on RTX8000 (VRAM: 48GB).
How much VRAM does it take, for example, ```python train_mlg.py --config config/Lineformer/chest_50.yaml``` ?
With V100 (VRAM: 16GB), I got an OOM error.

I would appreciate it if you could let me know.
Thank you in advance.

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest. For `chest` scene. It only takes 4194 MB GPU memory on the RTX 8000 GPU. It is weird that you could not run. Could you please share the error information? 

![image](https://github.com/caiyuanhao1998/SAX-NeRF/assets/48472661/f628c796-a1ec-413c-9e26-51c72ede0c91)

**Comment by caiyuanhao1998** [comment]
were there other processes on the GPU you ran?

**Comment by caiyuanhao1998** [comment]
Hello? Does this issue still block you?

**Comment by mit-mit-pg** [comment]
I am very sorry for the late reply.
As a conclusion, I checked again and the problem has been resolved.
It only consumed approximately 4200 MB of VRAM in my environment as well.

The cause was that I was unintentionally using the default value GPU1 (instead of 0) and another process was running on GPU1.

Sorry for the confusion.
Thank you very much.

**Comment by caiyuanhao1998** [comment]
Sounds good. Enjoy!
